spring.application.name=garage
spring.datasource.url=jdbc:sqlite:racing.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Permet à Hibernate de créer les tables automatiquement selon tes classes Java
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect
